services:
  zookeeper:
    image: zookeeper:3.9.2
    container_name: "zookeeper"
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - pinot-network
    healthcheck:
      test: ["CMD", "zkServer.sh", "status"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: "prometheus"
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ../jmx_exporter/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - pinot-network

  kafka:
    image: bitnami/kafka:3.6
    container_name: "kafka"
    restart: unless-stopped
    ports:
      - "9092:9092"   # container
      - "29092:29092" # localhost
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_OPTS: "-javaagent:/usr/share/jmx_prometheus_javaagent-1.2.0.jar=19092:/usr/share/kafka_jmx_config.yml"
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - pinot-network
    healthcheck:
      test: [ "CMD-SHELL", "env -u KAFKA_OPTS kafka-broker-api-versions.sh -bootstrap-server kafka:9092 || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      replicas: ${KAFKA_REPLICAS:-1}
    volumes:
      - ../jmx_exporter:/usr/share/

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.5
    container_name: schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:9092"
      SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
    networks:
      - pinot-network
    restart: "no"
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  pinot-controller:
    image: robertglowacki83/apache-pinot:1.2.0
    command: "StartController -zkAddress zookeeper:2181"
    container_name: "pinot-controller"
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms1G -Xmx2G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xlog:gc:gc-pinot-controller.log -javaagent:/opt/pinot/etc/jmx_prometheus_javaagent/jmx_prometheus_javaagent.jar=19000:/opt/pinot/etc/jmx_prometheus_javaagent/configs/controller.yml"
      AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - pinot-network
      -
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  pinot-broker:
    image: robertglowacki83/apache-pinot:1.2.0
    command: "StartBroker -zkAddress zookeeper:2181"
    container_name: "pinot-broker"
    restart: unless-stopped
    ports:
      - "8099:8099"
    environment:
      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms1G -Xmx2G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xlog:gc:gc-pinot-broker.log -javaagent:/opt/pinot/etc/jmx_prometheus_javaagent/jmx_prometheus_javaagent.jar=18099:/opt/pinot/etc/jmx_prometheus_javaagent/configs/broker.yml"
    depends_on:
      pinot-controller:
        condition: service_healthy
    networks:
      - pinot-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8099/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  pinot-server:
    image: robertglowacki83/apache-pinot:1.2.0
    command: "StartServer -zkAddress zookeeper:2181"
    container_name: "pinot-server"
    restart: unless-stopped
    ports:
      - "8098:8098"
      - "8097:8097"
    environment:
      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms2G -Xmx8G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xlog:gc:gc-pinot-server.log -javaagent:/opt/pinot/etc/jmx_prometheus_javaagent/jmx_prometheus_javaagent.jar=18098:/opt/pinot/etc/jmx_prometheus_javaagent/configs/server.yml"
    depends_on:
      pinot-broker:
        condition: service_healthy
    networks:
      - pinot-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8097/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  pinot-minion:
    image: robertglowacki83/apache-pinot:1.2.0
    command: "StartMinion -zkAddress zookeeper:2181"
    container_name: "pinot-minion"
    restart: unless-stopped
    ports:
      - "7500:7500"
    environment:
      JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms1G -Xmx2G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xlog:gc:gc-pinot-minion.log -javaagent:/opt/pinot/etc/jmx_prometheus_javaagent/jmx_prometheus_javaagent.jar=17500:/opt/pinot/etc/jmx_prometheus_javaagent/configs/minion.yml"
    AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
    depends_on:
      pinot-server:
        condition: service_healthy
    networks:
      - pinot-network

  kafka-producer:
    image: robertglowacki83/kafka-producer-app:1.0.0
    container_name: "kafka-producer-app"
    restart: no
    depends_on:
      pinot-server:
        condition: service_healthy
    networks:
      - pinot-network

networks:
  pinot-network:
    name: pinot-network
    driver: bridge
    external: true