# Start from the base Pinot image
FROM apachepinot/pinot:1.2.0

# Define build-time arguments
ENV OUTPUT_DIR=/opt/pinot/scripts

# Create directories for schema and table creation scripts
RUN mkdir -p ${OUTPUT_DIR}

# Copy the scripts into the image
COPY  cluster-setup/scripts/*.json /opt/pinot/scripts/

# Make the script executable
RUN chmod +x /opt/pinot/scripts/*.json