# Start from the base Pinot image
FROM apachepinot/pinot:1.2.0

# Define build-time arguments
ENV OUTPUT_DIR=/opt/pinot/scripts

# Create directories for schema and table creation scripts
RUN mkdir -p ${OUTPUT_DIR}

# Copy the scripts into the image
COPY cluster-setup/table_config/* /opt/pinot/scripts/
COPY cluster-setup/pinot/* /opt/pinot/config/

# Fix line endings and make scripts executable
RUN sed -i 's/\r$//' /opt/pinot/scripts/add-tables.sh && \
    chmod +x /opt/pinot/scripts/* && \
    chmod +x /opt/pinot/config/*