apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: data-ops-center
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: kafka
          env:
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-0.kafka-headless.data-ops-center.svc.cluster.local:9093,2@kafka-1.kafka-headless.data-ops-center.svc.cluster.local:9093,3@kafka-2.kafka-headless.data-ops-center.svc.cluster.local:9093"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "2"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "2"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
              ephemeral-storage: 100Mi
            limits:
              cpu: 2
              memory: 2Gi
              ephemeral-storage: 500Mi
