apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: data-ops-center
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: zookeeper
          env:
            - name: ZOO_SERVERS
              value: "server.1=zookeeper-0.zookeeper-headless.data-ops-center.svc.cluster.local:2888:3888"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
              ephemeral-storage: 50Mi
            limits:
              cpu: 250m
              memory: 384Mi
              ephemeral-storage: 200Mi