# Start from the base Pinot image
FROM apachepinot/pinot:1.3.0

# Copy the additional scripts into the image
COPY /scripts/add*.sh /opt/pinot/scripts/

# Make the script executable
RUN chmod +x /opt/pinot/scripts/add*.sh