# Start from the base Pinot image
FROM apachepinot/pinot:1.2.0

# Define build-time arguments
ENV AVRO_DIR=/opt/pinot/avro
ENV OUTPUT_DIR=/opt/pinot/scripts

# Create directories for Avro schemas and scripts
RUN mkdir -p ${AVRO_DIR}
RUN mkdir -p ${OUTPUT_DIR}

# Copy the Avro schema file from the host to the container
COPY src/main/avro/*.avsc ${AVRO_DIR}/

# Run the AvroSchemaToPinotSchema command during the build process
RUN /opt/pinot/bin/pinot-admin.sh AvroSchemaToPinotSchema \
    -avroSchemaFile ${AVRO_DIR}/Trade.avsc \
    -pinotSchemaName "trade_table_schema" \
    -outputDir "${OUTPUT_DIR}" \
    -dimensions "eventId" \
    -timeColumnName="eventTime"

# Copy the scripts into the image /when not using the generated schema
# COPY /scripts/*.sh /opt/pinot/scripts/

# Make the script executable
# RUN chmod +x /opt/pinot/scripts/*.sh