apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: data-ops-center
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: kafka
          env:
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-0.kafka-headless.data-ops-center.svc.cluster.local:9093"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "1"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_NUM_PARTITIONS
              value: "1"
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
              ephemeral-storage: 100Mi
            limits:
              cpu: 500m
              memory: 768Mi
              ephemeral-storage: 500Mi
