{
 "title": "Pinot",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Controller Leader",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (pinot_controller_LeaderPartitionCount_Value)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Table Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pinot_controller_realtimeTableCount_Value)",
     "legendFormat": "total realtime table count"
    },
    {
     "expr": "sum(pinot_controller_offlineTableCount_Value)",
     "legendFormat": "total offline table count"
    }
   ]
  },
  {
   "title": "Table Query QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (rate(pinot_broker_queries_Count[10m]))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Table Query Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (table) (pinot_broker_queryExecution_50thPercentile) ",
     "legendFormat": "{{table}}-p50"
    },
    {
     "expr": "avg by (table) (pinot_broker_queryExecution_75thPercentile)",
     "legendFormat": "{{table}}-p75"
    },
    {
     "expr": "avg by (table) (pinot_broker_queryExecution_95thPercentile)",
     "legendFormat": "{{table}}-p95"
    },
    {
     "expr": "avg by (table) (pinot_broker_queryExecution_99thPercentile)",
     "legendFormat": "{{table}}-p99"
    },
    {
     "expr": "avg by (table) (pinot_broker_queryExecution_999thPercentile)",
     "legendFormat": "{{table}}-p999"
    }
   ]
  },
  {
   "title": "Table Ingestion Data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (avg by (partition) (rate(pinot_server_realtimeRowsConsumed_Count[5m])))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum by (topic) (avg by (partition) (pinot_server_realtimeIngestionDelayMs_Value))",
     "legendFormat": "Delay"
    },
    {
     "expr": "rate(kafka_events_published_total[5m])",
     "legendFormat": "Published"
    }
   ]
  },
  {
   "title": "Table Consuming Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (table) (pinot_server_freshnessLagMs_50thPercentile)",
     "legendFormat": "{{table}}-p50"
    },
    {
     "expr": "avg by (table) (pinot_server_freshnessLagMs_75thPercentile)",
     "legendFormat": "{{table}}-p75"
    },
    {
     "expr": "avg by (table) (pinot_server_freshnessLagMs_95thPercentile)",
     "legendFormat": "{{table}}-p95"
    },
    {
     "expr": "avg by (table) (pinot_server_freshnessLagMs_99thPercentile)",
     "legendFormat": "{{table}}-p99"
    },
    {
     "expr": "avg by (table) (pinot_server_freshnessLagMs_999thPercentile)",
     "legendFormat": "{{table}}-p999"
    }
   ]
  },
  {
   "title": "Server Segment Build",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (pinot_server_llcSimultaneousSegmentBuilds_Value)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Pinot Instance CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (job) (rate(process_cpu_seconds_total[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Pinot Instance JVM Heap Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max by (job)(jvm_memory_used_bytes{area=\"heap\", job=~\"pinot-.*\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Server Query Processing Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (table) (pinot_server_queryProcessing_50thPercentile)",
     "legendFormat": "{{table}}-p50"
    },
    {
     "expr": "avg by (table) (pinot_server_queryProcessing_75thPercentile)",
     "legendFormat": "{{table}}-p75"
    },
    {
     "expr": "avg by (table) (pinot_server_queryProcessing_95thPercentile)",
     "legendFormat": "{{table}}-p95"
    },
    {
     "expr": "avg by (table) (pinot_server_queryProcessing_99thPercentile)",
     "legendFormat": "{{table}}-p99"
    },
    {
     "expr": "avg by (table) (pinot_server_queryProcessing_999thPercentile)",
     "legendFormat": "{{table}}-p999"
    }
   ]
  },
  {
   "title": "Server Total Query Time Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (table) (pinot_server_totalQueryTime_50thPercentile)",
     "legendFormat": "{{table}}-p50"
    },
    {
     "expr": "avg by (table) (pinot_server_totalQueryTime_75thPercentile)",
     "legendFormat": "{{table}}-p75"
    },
    {
     "expr": "avg by (table) (pinot_server_totalQueryTime_95thPercentile)",
     "legendFormat": "{{table}}-p95"
    },
    {
     "expr": "avg by (table) (pinot_server_totalQueryTime_99thPercentile)",
     "legendFormat": "{{table}}-p99"
    },
    {
     "expr": "avg by (table) (pinot_server_totalQueryTime_999thPercentile)",
     "legendFormat": "{{table}}-p999"
    }
   ]
  },
  {
   "title": "Pinot Server Off-Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (pinot_server_realtime_offheapMemoryUsed_Value)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Pinot Server Memory Mapped Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (job) (pinot_server_mmapBufferUsage_Value)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Server Total Documents Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (pinot_server_documentCount_Value)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Server Total Segment Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (pinot_server_segmentCount_Value)",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Pinot Server Documents Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (pinot_server_documentCount_Value)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Pinot Server Segments Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (pinot_server_segmentCount_Value)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Server Query Doc Scanned Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (rate(pinot_server_numDocsScanned_Count[10m]))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Server Query Doc Scanned",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (job) (rate(pinot_server_numDocsScanned_Count[10m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Server Query Segment Processed Per Table",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (rate(pinot_server_numSegmentsProcessed_Count[5m]))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "Server Query Segment Processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (job) (rate(pinot_server_numSegmentsProcessed_Count[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Server DirectBuffer Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (pinot_server_directBufferUsage_Value)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Pinot Instance Old Gen Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max by (job)(jvm_memory_pool_used_bytes{pool=\"G1 Old Gen\", job=~\"pinot-.*\"})",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}