global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9091']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'pinot-controller'
    static_configs:
      - targets: ['pinot-controller:9000']

  - job_name: 'pinot-broker'
    static_configs:
      - targets: ['pinot-broker:8099']

  - job_name: 'pinot-server'
    static_configs:
      - targets: ['pinot-server:8098']

  - job_name: 'pinot-minion'
    static_configs:
      - targets: ['pinot-minion:7500']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:2181']

  - job_name: 'schema-registry'
    static_configs:
      - targets: ['schema-registry:8081']
