{
    "tableName": "topic",
    "tableType": "REALTIME",
    "segmentsConfig": {
		"minimizeDataMovement": false,
		"timeColumnName": "eventTime",
		"timeType": "MILLISECONDS",
		"schemaName": "topic",
		"replicasPerPartition": "1"
    },
    "tenants": {
		"broker": "DefaultTenant",
		"server": "DefaultTenant"
    },
    "tableIndexConfig": {
		"loadMode": "MMAP",
		"streamConfigs": {
			"streamType": "kafka",
			"stream.kafka.consumer.type": "lowlevel",
			"stream.kafka.topic.name": "topic",
			"stream.kafka.decoder.class.name": "org.apache.pinot.plugin.stream.kafka.KafkaJSONMessageDecoder",
			"stream.kafka.consumer.factory.class.name": "org.apache.pinot.plugin.stream.kafka20.KafkaConsumerFactory",
			"stream.kafka.broker.list": "kafka:9092",
			"realtime.segment.flush.threshold.rows": "0",
			"realtime.segment.flush.threshold.time": "24h",
			"realtime.segment.flush.threshold.segment.size": "50M",
			"stream.kafka.consumer.prop.auto.offset.reset": "smallest",
			"stream.kafka.consumer.prop.request.timeout.ms": "30000",
			"stream.kafka.consumer.prop.fetch.metadata.timeout.ms": "30000"
		},
		"enableDefaultStarTree": false,
		"enableDynamicStarTreeCreation": false,
		"aggregateMetrics": false,
		"nullHandlingEnabled": false,
		"columnMajorSegmentBuilderEnabled": true,
		"optimizeDictionary": false,
		"optimizeDictionaryForMetrics": false,
		"noDictionarySizeRatioThreshold": 0.85,
		"rangeIndexVersion": 2,
		"autoGeneratedInvertedIndex": false,
		"createInvertedIndexDuringSegmentGeneration": false
    },
	"ingestionConfig": {
		"transformConfigs": [
			{
				"columnName": "eventTime",
				"transformFunction": "now()"
			}
		]
	},
    "metadata": {
		"customConfigs": {}
    },
    "isDimTable": false
}