name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      KAFKA_PRODUCER_MODULE: kafka-producer-app
      APACHE_PINOT: apache-pinot

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install xmllint
      run: sudo apt-get update && sudo apt-get install -y libxml2-utils

    - name: Extract kafka producer app version from pom.xml
      id: extract_version
      run: |
        VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" $KAFKA_PRODUCER_MODULE/pom.xml)
        echo "VERSION=$VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build and push Docker image of kafka producer app
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./${{ env.KAFKA_PRODUCER_MODULE }}/Dockerfile.${{ env.KAFKA_PRODUCER_MODULE }}
        push: true
        tags: |
          docker.io/${{ vars.DOCKER_USERNAME }}/${{ env.KAFKA_PRODUCER_MODULE }}:${{ steps.extract_version.outputs.version }}

    - name: Extract Pinot version
      id: extract_version
      run: |
        echo "version=$(grep -oP 'FROM apachepinot/pinot:\K[\d.]+' ./cluster-setup/Dockerfile.${{ env.APACHE_PINOT }})" >> $GITHUB_OUTPUT

    - name: Build and push Docker image of custom Apache Pinot app
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./cluster-setup/Dockerfile.${{ env.APACHE_PINOT }}
        push: true
        tags: |
          docker.io/${{ vars.DOCKER_USERNAME }}/${{ env.APACHE_PINOT }}::${{ steps.extract_version.outputs.version }}