name: Fetch data

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_BUCKET: ${{ vars.AWS_BUCKET_GDANSK_PUBLIC_TRANSPORT }}
      ROLE_ARN: arn:aws:iam::689522024200:role/S3AccessRole

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install -r .github/workflows/requirements.txt

      - run: python cluster-setup/py/gdansk_public_transport_github_action.py

      - name: Calculate date time
        id: time
        run: |
          NOW=$(date -u +"%Y-%m-%d-%H-%M")
          YEAR=$(date -u +"%Y")
          MONTH=$(date -u +"%m")
          DAY=$(date -u +"%d")
          FILENAME="./${NOW}.txt"
          DEST_DIR="${YEAR}/${MONTH}/${DAY}"
          echo "file=${FILENAME}" >> $GITHUB_OUTPUT
          echo "date_dir=${DEST_DIR}" >> $GITHUB_OUTPUT


      - name: Debug file listing
        run: ls -la

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp ${{ steps.time.outputs.file }} s3://${{ env.AWS_BUCKET }}/${{ steps.time.outputs.date_dir }}/
