name: Fetch data and upload to S3

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"  # Runs at the start of every hour (UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      AWS_BUCKET: ${{ vars.AWS_BUCKET_GDANSK_PUBLIC_TRANSPORT }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r .github/workflows/requirements.txt
      - run: python cluster-setup/py/gdansk_public_transport.py
      - name: Get previous hour's filename
        id: previous-hour
        run: |
          PREVIOUS_HOUR=$(date -u -d "-1 hour" +"%Y-%m-%d-%H")
          echo "previous_hour=${PREVIOUS_HOUR}.txt" >> $GITHUB_OUTPUT
      - name: Upload previous hour's file to S3
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-north-1"
          aws-bucket: ${{ vars.AWS_BUCKET_GDANSK_PUBLIC_TRANSPORT }}
          file-path: ./${{ steps.previous-hour.outputs.previous_hour }}
          destination-dir: "/data"
