name: Fetch data

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"  # Runs at the start of every hour (UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      AWS_BUCKET: ${{ vars.AWS_BUCKET_GDANSK_PUBLIC_TRANSPORT }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r .github/workflows/requirements.txt
      - run: python cluster-setup/py/gdansk_public_transport.py

      - name: Calculate previous hour and date
        id: time
        run: |
          PREV_HOUR=$(date -u -d "-1 hour" +"%Y-%m-%d-%H")
          DATE_DIR=$(date -u -d "-1 hour" +"%Y-%m-%d")
          echo "Previous hour: $PREV_HOUR"
          echo "Date dir: $DATE_DIR"
          echo "file=./${PREV_HOUR}.txt" >> $GITHUB_OUTPUT
          echo "date_dir=${DATE_DIR}" >> $GITHUB_OUTPUT

      - name: Debug file listing
        run: ls -la

      - name: Upload to S3
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-bucket: ${{ vars.AWS_BUCKET_GDANSK_PUBLIC_TRANSPORT }}
          file-path: ${{ steps.time.outputs.file }}
          destination-dir: "/${{ steps.time.outputs.date_dir }}"
