name: Deploy AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-north-1
      AWS_ACCESS_KEY_ID: ${{ secrets.LAMBDA_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.LAMBDA_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies and prepare zip
        run: |
          mkdir -p aws_lambda
          cd aws_lambda
          pip install requests -t .
          pip install schedule -t .
          pip install boto3 -t .
          cp ../cluster-setup/py/gdansk_public_transport.py .
#          zip -r function.zip .

      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: GdanskPublicTransportHandler
          code-artifacts-dir: aws_lambda
          handler: index.handler
          runtime: nodejs20.x
          dry-run: false
