name: Upload Data to S3

on:
  schedule:
    - cron: "0 * * * *"  # Every hour

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Calculate previous hour and date
        id: time
        run: |
          PREV_HOUR=$(date -u -d "-1 hour" +"%Y-%m-%d-%H")
          DATE_DIR=$(date -u -d "-1 hour" +"%Y-%m-%d")
          echo "file=./${PREV_HOUR}.txt" >> $GITHUB_OUTPUT
          echo "date_dir=${DATE_DIR}" >> $GITHUB_OUTPUT

      - name: Upload to S3
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-north-1"
          aws-bucket: ${{ vars.AWS_BUCKET_GDANSK_PUBLIC_TRANSPORT }}
          file-path: ${{ steps.time.outputs.file }}
          destination-dir: "/data/${{ steps.time.outputs.date_dir }}"